
CC = g++
CFLAGS=-std=c++17

main: main.cpp cola.o pila.o vector.o

cola.o: cola.cpp cola.hpp
	$(CC) $(CFLAGS) cola.cpp cola.hpp

#lista.o: lista.cpp lista.hpp
#	$(CC) $(CFLAGS) lista.cpp lista.hpp

#nodo.o: nodo.cpp nodo.hpp
#	$(CC) $(CFLAGS) nodo.cpp nodo.hpp

pila.o: pila.cpp pila.hpp
	$(CC) $(CFLAGS) pila.cpp pila.hpp

vector.o: vector.cpp vector.hpp
	$(CC) $(CFLAGS) vector.cpp vector.hpp


